# Additional configuration and default values at https://github.com/gakonst/foundry/tree/master/config
[profile.default]

# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
# solc_version = '0.8.0'

remappings = [
  "ds/=lib/ds-test/src/",
  "@std=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
  "@aragon/=lib/osx/packages/contracts/src/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"

]

[profile.ci]
fuzz_runs = 2_000
